# Generated by Django 4.0.3 on 2022-04-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_cart',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='vitrina/images'),
        ),
    ]
